{{- if .Values.customApp.configEnabled }}
{{- if .Values.customApp.customAppConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "quark.fullname" . }}-customApp-config
  labels:
    app: "{{ template "quark.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
{{- range $path, $config := .Values.customApp.customAppConfig }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}
{{- end -}}