apiVersion: v1
kind: Service
metadata:
  name: {{ include "quark.fullname" . }}
  labels:
    {{- include "quark.labels" . | nindent 4 }}
spec:
  {{- if .Values.customApp.dubboSet.dubboPort }}
  type: NodePort
  {{- else }}
  type: {{ .Values.customApp.service.type }}
  {{- end }}
  {{- if .Values.customApp.service.externalIPs }}
  externalIPs:
  {{ toYaml .Values.customApp.service.externalIPs | indent 4 }}
  {{- end }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.customApp.service.port }}
      targetPort: {{ .Values.customApp.service.port }}
      nodePort: {{ .Values.customApp.service.nodePort }}
      {{- if .Values.customApp.dubboSet.dubboPort }}
    - name: dubbo
      port: {{ .Values.customApp.dubboSet.port }}
      nodePort: {{ .Values.customApp.dubboSet.port }}
      targetPort: {{ .Values.customApp.dubboSet.port }}
    {{- end }}
    {{- range $index, $port := .Values.customApp.extraPorts }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      nodePort: {{ $port.nodePort }}
      targetPort: {{ $port.port }}
    {{- end }}
  selector:
    {{- include "quark.selectorLabels" . | nindent 4 }}